# Copyright 2020 ChainSafe Systems
# SPDX-License-Identifier: LGPL-3.0-only

# version: "3"
services:
  geth1:
    image: "chainsafe/chainbridge-geth:20200505131100-5586a65"
    container_name: geth1
    ports:
      - "8545:8545"
    volumes:
      - ./geth-root/genesis.json:/root/genesis.json:ro
      - ./geth-root/entrypoint.sh:/root/entrypoint.sh:ro
    command:
      - --http.vhosts=*
    networks:
      - default

  geth2:
    image: "chainsafe/chainbridge-geth:20200505131100-5586a65"
    container_name: geth2
    ports:
      - "8555:8545"
    volumes:
      - ./geth-root/genesis.json:/root/genesis.json:ro
      - ./geth-root/entrypoint.sh:/root/entrypoint.sh:ro
    command:
      - --http.vhosts=*
    networks:
      - default

  setup_onchain:
    image: phalanetwork/chainbridge-deploy
    container_name: setup_onchain
    depends_on:
      - geth1
      - geth2
    env_file: .env
    volumes:
      - ./on_chain_setup.sh:/usr/local/bin/startscript.sh:ro
    command: /bin/sh -c "/usr/local/bin/startscript.sh"
    networks:
      - default

  alice_relayer:
    image: chainsafe/chainbridge:v1.1.5
    container_name: alice_relayer
    depends_on:
      setup_onchain:
        condition: service_completed_successfully
    volumes:
      - ./config/alice.json:/config.json:ro
    command:
      - --testkey=alice
      - --latest
    networks:
      - default

  bob_relayer:
    image: chainsafe/chainbridge:v1.1.5
    container_name: bob_relayer
    depends_on:
      setup_onchain:
        condition: service_completed_successfully
    volumes:
      - ./config/bob.json:/config.json:ro
    command:
      - --testkey=bob
      - --latest
    networks:
      - default

  charlie_relayer:
    image: chainsafe/chainbridge:v1.1.5
    container_name: charlie_relayer
    depends_on:
      setup_onchain:
        condition: service_completed_successfully
    volumes:
      - ./config/charlie.json:/config.json:ro
    command:
      - --testkey=charlie
      - --latest
    networks:
      - default
